### ISSUE TITLE
Is there a need to have compass and grunt?

### ISSUE THREAD

**Issue by rememberlenny** [alademann/bootstrap#13]
Wondering about using this as a base for some projects.

**Comment by alademann** [comment]
Not sure I follow... do you mean - is there a need for you to have compass and grunt installed in order to use sass-bootstrap? Or do you mean is it necessary for me to use the two tools to build the assets for your use? 

Either way - the answer is most likely yes.  The only way its not necessary for you to have them both is if you fork this repo, and in your personal fork - you create your own build system that compiles the sass, unit tests the plugins, etc... 

But to be honest - I have no idea why you would want to do that. 

Are you having trouble installing compass and/or grunt???

**Comment by rememberlenny** [comment]
Hey! Thanks for the prompt response.

Im not having any issues installing it. Rather, compass and Grunt compile files, so I don't understand why you don't just build a SASS compiler into grunt, so you only need to run one task runner. I don't see the need for having both if SASS is only being used to compile code.

## Thanks again.

Leonard Bogdonoff
@rememberlenny (http://twitter.com/rememberlenny) | http://lkb.cc
949-322-8496

**Comment by rememberlenny** [comment]
Specifically, there is a Grunt-SASS plugin that could be used. There is also a Grunt-Compass plugin if the dev/prod code compilation modes are valuable.

[Grunt-SASS](https://github.com/sindresorhus/grunt-sass) by [sindresorhus](https://github.com/sindresorhus)
[Grunt-Compass](https://github.com/gruntjs/grunt-contrib-compass) by [sindresorhus](https://github.com/sindresorhus)

**Comment by alademann** [comment]
Running grunt does compile the Sass. There is even a grunt task that watches for changes using LiveReload. Please refer to the Readme on the homepage of this repo.

Thanks,

Aaron

**Comment by rememberlenny** [comment]
@alademann :100: 
I missed the SCSS module when I looked through it the first time. Thanks for making this!
