### ISSUE TITLE
error with mixins.scss is anyone else getting this?

### ISSUE THREAD

**Issue by icemancast** [alademann/bootstrap#19]
error _mixins.scss (Line 783: Invalid CSS after "comma-list": expected selector, was "(), comma-list(...")

**Comment by alademann** [comment]
@icemancast - do you have compass installed?

**Comment by icemancast** [comment]
Ahhh no not using compass. Do I have to use compass or can I use it without?

**Comment by alademann** [comment]
Compass is just used as the compiler... `gem install compass` ... and you're set.

**Comment by alademann** [comment]
Also - if you simply run the `grunt` commands described in the Readme - e'thing should compile like a dream.

**Comment by GeorgeR** [comment]
This doesn't work for me either in VS2012 with WebWorkbench (it compiles SASS/Compass). The culprit is that comma-list() thing, and I can't see where it even gets resolved (unless its an internal compass thing). It might also be that I don't have the compass import (see the main sass-bootstrap.scss file). Is it that, and if so, where do I find it?

**Comment by alademann** [comment]
This repo is no longer supported - you should use the [official Sass Bootstrap Port](https://github.com/twbs/bootstrap-sass) from now-on.
